GRANT SELECT ON bds.categories TO 'RE_KhachHangThanThiet';
GRANT INSERT, UPDATE ON bds.comment TO 'RE_KhachHangThanThiet';
GRANT INSERT, UPDATE ON bds.convenient TO 'RE_KhachHangThanThiet';
GRANT SELECT ON bds.district TO 'RE_KhachHangThanThiet';
GRANT SELECT ON bds.medias TO 'RE_KhachHangThanThiet';
GRANT SELECT,INSERT, UPDATE, DELETE ON bds.posts TO 'RE_KhachHangThanThiet';
GRANT SELECT ON bds.project TO 'RE_KhachHangThanThiet';
GRANT SELECT ON bds.province TO 'RE_KhachHangThanThiet';
GRANT SELECT,INSERT ON bds.report TO 'RE_KhachHangThanThiet';
GRANT SELECT,INSERT, DELETE ON bds.savePosts TO 'RE_KhachHangThanThiet';
GRANT SELECT ON bds.street TO 'RE_KhachHangThanThiet';
GRANT SELECT,INSERT, UPDATE ON bds.users TO 'RE_KhachHangThanThiet';
GRANT SELECT ON bds.ward TO 'RE_KhachHangThanThiet';
