/*
CREATED		10/4/2022
MODIFIED		10/6/2022
PROJECT		
MODEL		
COMPANY		
AUTHOR		
VERSION		
DATABASE		MYSQL 5 
*/
CREATE DATABASE IF NOT EXISTS `BDS` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE `BDS`;

CREATE TABLE REALESTATES (
	REID CHAR(40) NOT NULL,
	CATEGORYID CHAR(40) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	PRICE DECIMAL(15,2) NOT NULL,
	AREA VARCHAR(100) NOT NULL,
	VIEW INT NOT NULL DEFAULT 0,
	APPROVE TINYINT NOT NULL DEFAULT 0,
	PHONE VARCHAR(20) NOT NULL,
	ADDRESS VARCHAR(255) NOT NULL,
	COORDINATE VARCHAR(255) NOT NULL,
	RENTED TINYINT NOT NULL DEFAULT 0,
	CREATEDAT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UPDATEDAT TIMESTAMP,
	USERID CHAR(40) NOT NULL,
	WARDID CHAR(40) NOT NULL,
	DISTRICTID CHAR(40) NOT NULL,
	CITYID CHAR(40) NOT NULL,
 PRIMARY KEY (REID)) ENGINE = MYISAM;

CREATE TABLE USERS (
	USERID CHAR(40) NOT NULL ,
	NAME VARCHAR(255) NOT NULL,
	USERNAME VARCHAR(150) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(255) NOT NULL,
	TYPEUSER TINYINT NOT NULL DEFAULT 0,
	PHONE VARCHAR(255) NOT NULL,
	AVATAR TEXT,
	CREATEDAT TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
	UPDATEDAT TIMESTAMP,
	STATUS TINYINT NOT NULL DEFAULT 0,
 PRIMARY KEY (USERID)) ENGINE = MYISAM;

CREATE TABLE CITIES (
	NAME VARCHAR(255) NOT NULL,
	CITYID CHAR(40) NOT NULL ,
	UNIQUE (NAME),
 PRIMARY KEY (CITYID)) ENGINE = MYISAM;

CREATE TABLE DISTRICTS (
	DISTRICTID CHAR(40) NOT NULL ,
	CITYID CHAR(40) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
 PRIMARY KEY (DISTRICTID,CITYID)) ENGINE = MYISAM;

CREATE TABLE WARDS (
	NAME VARCHAR(255) NOT NULL,
	WARDID CHAR(40) NOT NULL ,
	DISTRICTID CHAR(40) NOT NULL,
	CITYID CHAR(40) NOT NULL,
 PRIMARY KEY (WARDID,DISTRICTID,CITYID)) ENGINE = MYISAM;

CREATE TABLE CONVENIENT (
	CONVENIENTID CHAR(40) NOT NULL,
	NAME VARCHAR(255) NOT NULL,
 PRIMARY KEY (CONVENIENTID)) ENGINE = MYISAM;

CREATE TABLE IMAGES (
	IMAGEID CHAR(40) NOT NULL ,
	URL TEXT NOT NULL,
	REID CHAR(40) NOT NULL,
 PRIMARY KEY (IMAGEID)) ENGINE = MYISAM;

CREATE TABLE CATEGORIES (
	CATEGORYID CHAR(40) NOT NULL ,
	NAME VARCHAR(255) NOT NULL,
 PRIMARY KEY (CATEGORYID)) ENGINE = MYISAM;

CREATE TABLE REALESTATE_CONVENIENT (
	CONVENIENTID CHAR(40) NOT NULL,
	REID CHAR(40) NOT NULL,
	CONTENT VARCHAR(255) NOT NULL,
 PRIMARY KEY (CONVENIENTID,REID)) ENGINE = MYISAM;

CREATE TABLE COMMENT (
	COMMENTID CHAR(40) NOT NULL,
	CREATEDAT TIMESTAMP NOT NULL,
	CONTENT TEXT NOT NULL,
	REID CHAR(40) NOT NULL,
	USERID CHAR(40) NOT NULL,
 PRIMARY KEY (COMMENTID)) ENGINE = MYISAM;

CREATE TABLE REPORT (
	REPORTID CHAR(40) NOT NULL,
	REID CHAR(40) NOT NULL,
	PHONE VARCHAR(20),
	EMAIL VARCHAR(255),
	CONTENTRP TEXT NOT NULL,
	CREATEDAT TIMESTAMP NOT NULL DEFAULT  CURRENT_TIMESTAMP,
 PRIMARY KEY (REPORTID)) ENGINE = MYISAM;


ALTER TABLE IMAGES ADD FOREIGN KEY (REID) REFERENCES REALESTATES (REID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE REALESTATE_CONVENIENT ADD FOREIGN KEY (REID) REFERENCES REALESTATES (REID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE COMMENT ADD FOREIGN KEY (REID) REFERENCES REALESTATES (REID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE REPORT ADD FOREIGN KEY (REID) REFERENCES REALESTATES (REID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE REALESTATES ADD FOREIGN KEY (USERID) REFERENCES USERS (USERID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE COMMENT ADD FOREIGN KEY (USERID) REFERENCES USERS (USERID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE DISTRICTS ADD FOREIGN KEY (CITYID) REFERENCES CITIES (CITYID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE WARDS ADD FOREIGN KEY (DISTRICTID,CITYID) REFERENCES DISTRICTS (DISTRICTID,CITYID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE REALESTATES ADD FOREIGN KEY (WARDID,DISTRICTID,CITYID) REFERENCES WARDS (WARDID,DISTRICTID,CITYID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE REALESTATE_CONVENIENT ADD FOREIGN KEY (CONVENIENTID) REFERENCES CONVENIENT (CONVENIENTID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;
ALTER TABLE REALESTATES ADD FOREIGN KEY (CATEGORYID) REFERENCES CATEGORIES (CATEGORYID) ON DELETE  RESTRICT ON UPDATE  RESTRICT;


/* USERS PERMISSIONS */


